spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/PriceAnalyzeWithSecurity
    username: postgres
    password: 01
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  mvc:
    view:
      prefix: /static/
      suffix: .html